import 'dart:async';
import 'dart:math' as math;
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:gal/gal.dart';
import 'package:visibility_detector/visibility_detector.dart';

import '../../api/models.dart';
import '../../theme/accent.dart';
import '../../theme/tokens.dart';
import '../../widgets/feed_autoplay.dart';
import '../../widgets/media_frame.dart';
import '../../widgets/photo_viewer.dart';
import '../../widgets/user_avatar.dart';
import '../post/post_detail_screen.dart';

const _bgSurface = kBgSurface;
const _bgSurfaceHover = kBgSurfaceHover;
const _border = kBorder;
const _fgPrimary = kFgPrimary;
const _fgSecondary = kFgSecondary;
const _fgMuted = kFgMuted;

/// RecapDeck renders a recap post's panels as a swipeable, PageView deck: a cover page
/// (the group's own moment - see [_RecapCoverPage]) followed by whichever panels the
/// payload carries - the collage ("The Wall") in every recap generated by this server
/// version, or awards ("Awards Night") too on a deck generated by an older one still
/// sitting in the feed (Awards Night itself is retired; profile titles replaced it).
///
/// A panel type this client doesn't recognise never reaches here at all: [Post.fromJson]
/// drops it via [RecapPanel.tryParse], which is the forward-compat contract that lets a
/// v1.5+ server add new panel types without breaking this client. When that leaves zero
/// panels, the deck falls back to a plain stats summary (no cover either) rather than
/// rendering nothing.
class RecapDeck extends StatefulWidget {
  const RecapDeck({super.key, required this.recap, required this.groupId, required this.postId});

  final RecapPayload recap;
  final String? groupId;

  /// The recap post's own id - carried through to the cover for its avatar-bubble cluster,
  /// which seeds its jittered layout from it (see _BubbleCluster's doc comment).
  final int postId;

  @override
  State<RecapDeck> createState() => RecapDeckState();
}

/// Public so [PostCard] can reach [saveCurrentPage] through a [GlobalKey] - the overflow
/// menu's "Save this panel" item lives on the post card, not the deck, matching where every
/// other post's save action lives (see post_card.dart's PopupMenuButton).
class RecapDeckState extends State<RecapDeck> {
  final _controller = PageController();
  final Map<int, GlobalKey> _boundaryKeys = {};
  int _page = 0;

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  GlobalKey _keyFor(int index) => _boundaryKeys.putIfAbsent(index, () => GlobalKey());

  /// Rasterizes whichever page the deck is currently showing and saves it - what the post
  /// card's overflow-menu "Save this panel" item calls.
  Future<void> saveCurrentPage() => _savePanel(_page);

  /// Rasterizes the current panel's [RepaintBoundary] and saves it to the device gallery -
  /// the v1 "generated image" flow. Zero new dependencies: both halves already exist
  /// in-tree (photo_crop_screen.dart's capture, post_card.dart's Gal save).
  Future<void> _savePanel(int index) async {
    try {
      final boundary = _keyFor(index).currentContext!.findRenderObject() as RenderRepaintBoundary;
      final pixelRatio = (1080.0 / boundary.size.width).clamp(1.0, 4.0);
      final image = await boundary.toImage(pixelRatio: pixelRatio);
      final data = await image.toByteData(format: ui.ImageByteFormat.png);
      image.dispose();
      if (data == null) return;
      await Gal.putImageBytes(data.buffer.asUint8List());
      _snack('Saved to your photos');
    } on GalException catch (_) {
      _snack('Allow photo access to save this');
    } catch (_) {
      _snack('Could not save this panel');
    }
  }

  void _snack(String msg) {
    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(msg)));
  }

  @override
  Widget build(BuildContext context) {
    final panels = widget.recap.panels;
    if (panels.isEmpty) {
      return _RecapStatsFallback(recap: widget.recap);
    }
    final pages = _buildPages();
    final pageCount = pages.length;
    return Column(
      mainAxisSize: MainAxisSize.min,
      children: [
        AspectRatio(
          // Every page - the cover, an awards page, a chunked Wall page - shares this one
          // footprint; see _deckAspectRatio's own doc comment for the measurement behind it.
          aspectRatio: _deckAspectRatio,
          child: PageView.builder(
            controller: _controller,
            itemCount: pageCount,
            onPageChanged: (i) => setState(() => _page = i),
            itemBuilder: (context, index) => RepaintBoundary(
              key: _keyFor(index),
              child: pages[index],
            ),
          ),
        ),
        // Page dots only - saving now lives in the post card's overflow menu, alongside
        // every other post's save action (see PostCard's PopupMenuButton and
        // RecapDeckState.saveCurrentPage).
        _PageDots(pageCount: pageCount, page: _page),
      ],
    );
  }

  /// Flattens the recap's panels into the deck's actual pages: the cover, then one page per
  /// panel - except the collage ("The Wall"), which chunks its cards across as many pages as
  /// it takes to stay inside the deck's fixed footprint instead of overflowing a single page
  /// (see _WallPanel's and _deckAspectRatio's doc comments for how a chunk is kept from ever
  /// exceeding it). This is what fixes the round-3 regression: a 4-card (or 20-card) collage
  /// no longer clips its lower cards behind an unreachable, unscrollable grid - it gets its
  /// own extra deck pages instead, reachable the same way every other page already is:
  /// swiping.
  List<Widget> _buildPages() {
    final pages = <Widget>[
      _RecapCoverPage(recap: widget.recap, groupId: widget.groupId, postId: widget.postId),
    ];
    for (final panel in widget.recap.panels) {
      switch (panel) {
        case RecapCollagePanel p:
          final chunks = _chunkCards(p.cards, _wallCardsPerPage);
          for (final chunk in chunks) {
            // p.title ("The Wall") is deliberately never rendered - see _WallPanel's own
            // doc comment. It stays on the model/JSON only for a server that still expects
            // to read it back unchanged.
            pages.add(_WallPanel(cards: chunk, groupId: widget.groupId));
          }
        case RecapAwardsPanel p:
          pages.add(_AwardsPanel(panel: p, groupId: widget.groupId));
      }
    }
    return pages;
  }
}

/// How many Wall cards share one deck page - one 2x2 grid's worth (see _WallPanel), which is
/// also what a monthly recap's 20-card cap works out to: 5 Wall pages, 6 dots total with the
/// cover - the founder's own back-of-envelope number for what "up to 6 dots" should be.
const _wallCardsPerPage = 4;

/// The deck's page footprint: width:height. Portrait, not round 3's 4:3 - a 2x2 grid of
/// portrait (0.85-aspect) tiles needs more height than a 4:3 page has room for, which is what
/// let the second row go unreachable in the first place.
///
/// Round 4 landed on 3:4 (0.75) for this, with the Wall page still carrying its own panel
/// title ("The Wall") above the grid - real headroom rather than the calculated edge, but
/// still textScale-sensitive: the title's own text grew with textScaler (never clamped
/// anywhere in this app), eating into the grid's share of the page, which is why that
/// round's clearance shrank as scale grew (~27px at the default scale, ~20px at 1.3x, ~12px
/// at 1.6x).
///
/// Round 5 drops that title entirely (the founder found it redundant with the post card's
/// own header - see _WallPanel's doc comment), which changes the shape of this problem: the
/// Wall page's grid is now the page's *only* content, sized purely by this ratio and the
/// page's own fixed padding - nothing left in that layout scales with text at all, so
/// clearance is identical at every scale rather than shrinking at 1.3x/1.6x the way it used
/// to. That is what actually buys back the room to shrink the ratio itself: measured the same
/// way as round 4 (a 320dp-wide device, four cards, painted tile bounds against the page's
/// own), 0.84 clears the second row by ~19px, uniformly across 1.0x/1.3x/1.6x text scale -
/// comfortably past the "keep double-digit clearance, don't sit at the edge" bar this
/// measurement has to clear, while still noticeably shorter than 3:4 (roughly a tenth less
/// tall for the same width) - the actual "downsize it a bit" the founder asked for.
const _deckAspectRatio = 0.84;

/// Splits [cards] into consecutive groups of at most [size], preserving order. An empty
/// [cards] is never actually reached here - BuildRecap (recap.go) only ever appends a
/// collage panel when selectCollageCards returned at least one card - but this still
/// degrades to zero chunks rather than one empty one if that contract ever changes.
List<List<RecapCard>> _chunkCards(List<RecapCard> cards, int size) {
  final out = <List<RecapCard>>[];
  for (var i = 0; i < cards.length; i += size) {
    out.add(cards.sublist(i, math.min(i + size, cards.length)));
  }
  return out;
}

/// The deck's page-dot row. At or under [_maxDots] pages, every page still gets its own dot
/// - unchanged from before. Past it - only reachable with an oversized group, since
/// collageCardCap's memberCount floor can push the Wall's card cap (and so its page count)
/// well above the 20-card monthly default - the row instead shows a fixed-size sliding
/// window centred on the current page, so its rendered width stays bounded rather than
/// growing without limit and overflowing the row.
class _PageDots extends StatelessWidget {
  const _PageDots({required this.pageCount, required this.page});

  final int pageCount;
  final int page;

  static const _maxDots = 9;
  static const _window = 7;

  @override
  Widget build(BuildContext context) {
    final indices =
        pageCount <= _maxDots ? [for (var i = 0; i < pageCount; i++) i] : _windowedIndices();
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 10),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          for (final i in indices)
            Container(
              margin: const EdgeInsets.symmetric(horizontal: 3),
              width: i == page ? 16 : 6,
              height: 6,
              decoration: BoxDecoration(
                color: i == page ? context.accent : _border,
                borderRadius: BorderRadius.circular(3),
              ),
            ),
        ],
      ),
    );
  }

  List<int> _windowedIndices() {
    final start = (page - _window ~/ 2).clamp(0, pageCount - _window);
    return [for (var i = 0; i < _window; i++) start + i];
  }
}

/// The deck's first page: a system moment, not a normal post header. A slow cross-fading
/// montage of the period's own photos sits behind a pile of the period's posters' avatars
/// and the at-a-glance stats - what makes a recap post read as a group artifact at a glance
/// rather than one more check-in in the feed. The group's own name is deliberately not
/// repeated here - the post card's header already carries it (see post_card.dart's
/// group-name label next to the RECAP badge).
///
/// Stateful (round 5) so it can gate its two ambient animations - the backdrop montage and
/// the avatar cluster's entrance/float, see [_CoverBackdrop] and [_BubbleCluster] - behind
/// real on-screen visibility: this page sits in a scrolling feed, and a repeating ticker
/// nobody is looking at is exactly the leak feed_autoplay.dart already solved for clips (see
/// this class's own [_onVisibilityChanged], which copies that same activate/release/debounce
/// discipline).
class _RecapCoverPage extends StatefulWidget {
  const _RecapCoverPage({required this.recap, required this.groupId, required this.postId});

  final RecapPayload recap;
  final String? groupId;

  /// The recap post's own id, threaded down for the bubble cluster's deterministic seed -
  /// see _BubbleCluster's doc comment - and used as this page's own VisibilityDetector key.
  final int postId;

  @override
  State<_RecapCoverPage> createState() => _RecapCoverPageState();
}

class _RecapCoverPageState extends State<_RecapCoverPage> {
  bool _visible = false;
  Timer? _settle;

  /// Every card across every Wall chunk that carries a photo or clip, in the server's own
  /// rank order - the montage's source material. Capped rather than handing the backdrop
  /// every card a big monthly recap can carry: the montage only needs enough variety to
  /// read as "alive", not a slideshow of all twenty, and a shorter list also means a
  /// shorter full loop before it repeats.
  static const _montageCap = 8;

  List<PostMedia> get _photos {
    final out = <PostMedia>[];
    for (final panel in widget.recap.panels) {
      if (panel is RecapCollagePanel) {
        for (final card in panel.cards) {
          if (card.media != null) {
            out.add(card.media!);
            if (out.length >= _montageCap) return out;
          }
        }
      }
    }
    return out;
  }

  String get _eyebrow => switch (widget.recap.cadence) {
        'weekly' => 'WEEKLY RECAP',
        'monthly' => 'MONTHLY RECAP',
        _ => 'RECAP',
      };

  String get _statsLine {
    final s = widget.recap.stats;
    return [
      '${s.posts} ${s.posts == 1 ? 'check-in' : 'check-ins'}',
      '${s.places} ${s.places == 1 ? 'place' : 'places'}',
      '${s.members} ${s.members == 1 ? 'member' : 'members'}',
    ].join(' · ');
  }

  // No initState override to tune VisibilityDetectorController's batching interval here
  // (unlike feed_autoplay.dart's FeedAutoplayScope, which does): the recap cover sits inside
  // that same scope whenever it's in the main feed - by far the common case - so it already
  // gets that fast interval for free. Setting it again here would only fight a widget test
  // that has deliberately chosen `Duration.zero` for its own determinism (see
  // recap_card_test.dart), for no real benefit: the package's ordinary default just means a
  // cover reached some other way (a profile's post list, say) starts its ambient animation
  // up to half a second later, never something worth trading test control away for.

  @override
  void dispose() {
    _settle?.cancel();
    super.dispose();
  }

  /// Debounced the same way [FeedAutoplayController] debounces a clip's slot, and against
  /// the exact same thresholds ([FeedAutoplayController.activateAbove] /
  /// `.releaseBelow`) - reused rather than re-typed so the two "only animate while it's
  /// actually on screen" gates in this app can't quietly drift apart. A settle timer per
  /// cover rather than one shared timer: unlike the feed's one video slot, every recap
  /// cover's animation is independent, so there is no single winner to arbitrate.
  ///
  /// Guarded on [mounted] up front, not just inside the timer it schedules: the detector's
  /// last "gone invisible" report can arrive from its own layer-disposal callback after this
  /// State is already disposed (a card that's scrolled away and torn down in the same beat),
  /// and there is nothing useful left to debounce towards at that point - just a Timer this
  /// State will never get the chance to cancel.
  void _onVisibilityChanged(VisibilityInfo info) {
    if (!mounted) return;
    final fraction = info.visibleFraction;
    _settle?.cancel();
    _settle = Timer(const Duration(milliseconds: 200), () {
      if (!mounted) return;
      final next = fraction >= FeedAutoplayController.activateAbove
          ? true
          : fraction < FeedAutoplayController.releaseBelow
              ? false
              : _visible;
      if (next != _visible) setState(() => _visible = next);
    });
  }

  @override
  Widget build(BuildContext context) {
    final recap = widget.recap;
    final accent = accentById(recap.groupColor);
    final photos = _photos;
    const textShadows = [Shadow(color: Colors.black87, blurRadius: 10)];
    return VisibilityDetector(
      key: ValueKey('recap-cover-${widget.postId}'),
      onVisibilityChanged: _onVisibilityChanged,
      // The cover shares the wall pages' surface rather than tinting it with the group
      // accent: the tint only existed on page 0, so swiping to the wall read as the card
      // changing colour underneath you. The accent still marks the card, on its border ring
      // and the RECAP pill.
      child: DecoratedBox(
        decoration: const BoxDecoration(color: _bgSurface),
        child: Stack(
          fit: StackFit.expand,
          children: [
            // No photos this period (an awards-only historical deck, or a period that was
            // entirely quote cards) degrades to the plain background above - nothing extra
            // to guard here, see _CoverBackdrop's own empty-list branch.
            if (photos.isNotEmpty)
              _CoverBackdrop(photos: photos, groupId: widget.groupId, visible: _visible),
            DecoratedBox(
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  begin: Alignment.topCenter,
                  end: Alignment.bottomCenter,
                  colors: [
                    Colors.black.withValues(alpha: photos.isEmpty ? 0.05 : 0.35),
                    _bgSurface.withValues(alpha: 0.94),
                  ],
                ),
              ),
            ),
            // The people who posted this period, piled as a cluster of avatar bubbles sized
            // by contribution - the cover's "who's in this" moment. _BubbleCluster itself
            // renders nothing (see its empty-list guard) on a payload recorded before
            // RecapPayload.people existed, which just leaves the plain backdrop above as the
            // cover's whole focal point, same as it always has.
            Align(
              alignment: const Alignment(0, -0.1),
              child: _BubbleCluster(
                  people: recap.people,
                  seed: widget.postId,
                  groupId: widget.groupId,
                  visible: _visible),
            ),
            Padding(
              padding: const EdgeInsets.fromLTRB(20, 20, 20, 16),
              child: Column(
                mainAxisSize: MainAxisSize.min,
                mainAxisAlignment: MainAxisAlignment.end,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Container(
                    padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                    decoration: BoxDecoration(
                        color: accent.base, borderRadius: BorderRadius.circular(9999)),
                    child: Text(_eyebrow,
                        style: TextStyle(
                            color: accent.onAccent,
                            fontWeight: FontWeight.w800,
                            fontSize: 11,
                            letterSpacing: 1.1)),
                  ),
                  const SizedBox(height: 8),
                  // The period label carries the cover's headline weight now that the group
                  // name (already in the post card's header) isn't repeated here.
                  Text(recap.periodLabel,
                      style: const TextStyle(
                          color: Colors.white,
                          fontWeight: FontWeight.w700,
                          fontSize: 15,
                          shadows: textShadows)),
                  const SizedBox(height: 4),
                  Text(_statsLine,
                      style: TextStyle(
                          color: Colors.white.withValues(alpha: 0.95),
                          fontWeight: FontWeight.w600,
                          fontSize: 12,
                          shadows: textShadows)),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

/// The cover's animated backdrop: a slow cross-fade through [photos] with a subtle Ken
/// Burns-style scale drift, heavily blurred and dimmed so it reads as ambient texture behind
/// the avatar cluster and stats rather than competing with them.
///
/// A single [AnimationController] drives the whole cycle (duration scales with the photo
/// count, so a longer montage still has a sane pace per photo) rather than a per-transition
/// [Timer]: its progress alone determines which photo is showing, how far into that photo's
/// segment the crossfade to the next one has got, and the current scale - one animation, one
/// thing to start/stop/dispose, instead of a Timer and a controller that could fall out of
/// sync with each other.
///
/// Only ever built (see [_RecapCoverPageState.build]) when there is at least one photo, so
/// there is no empty-list branch here to worry about; the one-photo case still runs the
/// scale drift (there is simply never anything to crossfade to).
class _CoverBackdrop extends StatefulWidget {
  const _CoverBackdrop({required this.photos, required this.groupId, required this.visible});

  final List<PostMedia> photos;
  final String? groupId;

  /// Whether this cover is currently on screen - see _RecapCoverPageState's visibility gate.
  final bool visible;

  @override
  State<_CoverBackdrop> createState() => _CoverBackdropState();
}

class _CoverBackdropState extends State<_CoverBackdrop> with SingleTickerProviderStateMixin {
  AnimationController? _cycle;
  bool _reduceMotion = false;

  static const _secondsPerPhoto = 6;
  static const _crossfadeFraction = 0.28; // last ~28% of a photo's segment fades to the next
  static const _kenBurnsScale = 0.08; // grows from 1.0 to 1.08 across a photo's segment

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _reduceMotion = MediaQuery.of(context).disableAnimations;
    _sync();
  }

  @override
  void didUpdateWidget(_CoverBackdrop old) {
    super.didUpdateWidget(old);
    _sync();
  }

  /// Starts, resumes or stops the cycle to match [widget.visible] and [_reduceMotion].
  /// `.stop()` rather than disposing on every drop: a card that scrolls in and out
  /// repeatedly (an ordinary scroll wiggle near the viewport edge) resumes the montage where
  /// it left off instead of restarting the whole cycle each time.
  void _sync() {
    if (widget.visible && !_reduceMotion) {
      final c = _cycle ??= AnimationController(
        vsync: this,
        duration: Duration(seconds: _secondsPerPhoto * widget.photos.length),
      );
      if (!c.isAnimating) c.repeat();
    } else {
      _cycle?.stop();
    }
  }

  @override
  void dispose() {
    _cycle?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final photos = widget.photos;
    final cycle = _cycle;
    // Static (unstarted controller, or reduced motion): the first photo, at rest - exactly
    // what a single-photo montage looks like mid-cycle anyway, so this is not a visually
    // distinct "degraded" state, just a still frame of the same thing.
    if (cycle == null || _reduceMotion) return _layer(photos.first, scale: 1, opacity: 1);
    return AnimatedBuilder(
      animation: cycle,
      builder: (context, _) {
        final segment = 1.0 / photos.length;
        final raw = cycle.value / segment;
        final index = raw.floor().clamp(0, photos.length - 1);
        final localT = raw - index;
        final scale = 1 + _kenBurnsScale * localT;
        final fadeStart = 1 - _crossfadeFraction;
        final fadeT = localT <= fadeStart ? 0.0 : (localT - fadeStart) / _crossfadeFraction;
        return Stack(
          fit: StackFit.expand,
          children: [
            _layer(photos[index], scale: scale, opacity: 1),
            if (photos.length > 1 && fadeT > 0)
              _layer(photos[(index + 1) % photos.length], scale: 1, opacity: fadeT),
          ],
        );
      },
    );
  }

  Widget _layer(PostMedia media, {required double scale, required double opacity}) {
    return Opacity(
      // 0.32 is the layer's own full strength (matched to the old single-photo backdrop);
      // [opacity] on top of that is only ever <1 for the incoming crossfade layer.
      opacity: 0.32 * opacity,
      child: Transform.scale(
        scale: scale,
        child: ImageFiltered(
          imageFilter: ui.ImageFilter.blur(sigmaX: 20, sigmaY: 20),
          // A missing or failed (404) photo degrades to MediaFrame/AuthImage's own
          // placeholder - still a photo-shaped blurred rectangle, not a gap in the montage.
          child: MediaFrame(media: media, groupId: widget.groupId),
        ),
      ),
    );
  }
}

/// A pile of avatar bubbles for the people who posted this period, sized by contribution
/// (the biggest poster gets the biggest bubble) and packed into a jittered but deterministic
/// cluster - never a rigid grid, but the same recap always packs identically (see
/// [_packCircles]'s doc comment for why).
///
/// Round 5 adds two ambient touches on top of that same packing, deliberately kept out of
/// the packing itself: each bubble pops in with a staggered spring/scale entrance, then
/// drifts in a very subtle continuous float - a paint-only [Transform.translate]/
/// [Transform.scale] layered over each bubble's already-fixed [Positioned] slot, never a
/// change to the slot itself. That split is what keeps the layout deterministic (see the
/// "lays out identically across two builds" test, which this must still pass) while the
/// cluster still reads as alive rather than pasted onto the backdrop.
class _BubbleCluster extends StatefulWidget {
  const _BubbleCluster(
      {required this.people, required this.seed, required this.groupId, required this.visible});

  final List<RecapPerson> people;

  /// Seeds the layout's jitter - the recap post's own id (see _RecapCoverPage.postId), so
  /// the same recap always packs identically across rebuilds and app launches, while a
  /// different recap (a different id) packs differently. Deliberately never an unseeded
  /// `math.Random()`: that would reshuffle the pile on every single rebuild instead of only
  /// when the recap itself changes.
  final int seed;
  final String? groupId;

  /// Whether the cover is currently on screen - gates the continuous float (not the
  /// one-shot entrance, which is short and bounded enough to just play out on mount; see
  /// _BubbleClusterState's own doc comment).
  final bool visible;

  /// At most this many bubbles render as avatars; anyone past it is folded into a single
  /// "+N" bubble. [people] is already ordered by contribution desc (server-side), so the
  /// cap always drops the least active posters, not an arbitrary subset.
  static const _cap = 7;
  static const _minSize = 30.0;
  static const _maxSize = 62.0;

  /// Linear interpolation from the smallest to the largest bubble size, by this member's
  /// post count as a share of the top contributor's - the biggest poster gets the biggest
  /// bubble, everyone else scales down from there.
  static double _sizeFor(int posts, int maxPosts) {
    final t = (posts / maxPosts).clamp(0.0, 1.0);
    return _minSize + (_maxSize - _minSize) * t;
  }

  @override
  State<_BubbleCluster> createState() => _BubbleClusterState();
}

/// [_entrance] is a one-shot, bounded (~700ms) reveal: it starts as soon as this state knows
/// whether reduced motion is on (first [didChangeDependencies]) and is never gated on
/// [_BubbleCluster.visible] - a card built near the bottom of a feed's cache extent is
/// already about to be scrolled to, so playing the pop-in on mount rather than waiting for a
/// separate visibility confirmation reads as timely rather than delayed, and a controller
/// this short-lived is not the battery/jank concern the PERFORMANCE note is about.
///
/// [_float] is the opposite: unbounded (`..repeat()`) for as long as the cluster is on
/// screen, so it is exactly that concern - created only when [_BubbleCluster.visible] is
/// true, stopped the moment it isn't, disposed with everything else in [dispose].
class _BubbleClusterState extends State<_BubbleCluster> with TickerProviderStateMixin {
  late final AnimationController _entrance =
      AnimationController(vsync: this, duration: const Duration(milliseconds: 700));
  AnimationController? _float;
  bool _reduceMotion = false;
  bool _startedEntrance = false;

  static const _floatSeconds = 4;
  static const _floatAmplitude = 2.5; // px - subtle, not a bounce

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _reduceMotion = MediaQuery.of(context).disableAnimations;
    if (_reduceMotion) {
      _entrance.stop();
      _entrance.value = 1;
    } else if (!_startedEntrance) {
      _startedEntrance = true;
      _entrance.forward();
    }
    _syncFloat();
  }

  @override
  void didUpdateWidget(_BubbleCluster old) {
    super.didUpdateWidget(old);
    _syncFloat();
  }

  void _syncFloat() {
    if (widget.visible && !_reduceMotion && widget.people.isNotEmpty) {
      final f = _float ??=
          AnimationController(vsync: this, duration: const Duration(seconds: _floatSeconds));
      if (!f.isAnimating) f.repeat();
    } else {
      _float?.stop();
    }
  }

  @override
  void dispose() {
    _entrance.dispose();
    _float?.dispose();
    super.dispose();
  }

  /// This bubble's own slice of [_entrance]'s 0..1 timeline, offset by [index] so the
  /// cluster pops in one after another rather than all at once - a stagger, not a single
  /// synchronized scale.
  double _entranceT(int index, int count) {
    if (_reduceMotion) return 1;
    final start = count <= 1 ? 0.0 : (index / count) * 0.5;
    final curve = Interval(start, math.min(1.0, start + 0.5), curve: Curves.easeOutBack);
    return curve.transform(_entrance.value).clamp(0.0, 1.0);
  }

  /// A smooth, continuous vertical drift for bubble [index] - phase-shifted per index (by an
  /// irrational-ish offset, so bubbles never drift in lockstep) and ramped in by [entranceT]
  /// so the float never reads as a jump the instant a bubble finishes popping in.
  double _floatOffset(int index, double entranceT) {
    final f = _float;
    if (_reduceMotion || f == null) return 0;
    final phase = f.value * 2 * math.pi + index * 1.7;
    return math.sin(phase) * _floatAmplitude * entranceT;
  }

  @override
  Widget build(BuildContext context) {
    final people = widget.people;
    if (people.isEmpty) return const SizedBox.shrink();
    final shown = people.take(_BubbleCluster._cap).toList();
    final overflow = people.length - shown.length;
    final maxPosts = shown.first.posts <= 0 ? 1 : shown.first.posts;

    final radii = <double>[
      for (final p in shown) _BubbleCluster._sizeFor(p.posts, maxPosts) / 2,
      if (overflow > 0) _BubbleCluster._minSize / 2,
    ];
    final centers = _packCircles(radii, math.Random(widget.seed));

    var minX = double.infinity, minY = double.infinity;
    var maxX = -double.infinity, maxY = -double.infinity;
    for (var i = 0; i < centers.length; i++) {
      minX = math.min(minX, centers[i].dx - radii[i]);
      maxX = math.max(maxX, centers[i].dx + radii[i]);
      minY = math.min(minY, centers[i].dy - radii[i]);
      maxY = math.max(maxY, centers[i].dy + radii[i]);
    }

    return AnimatedBuilder(
      animation: _float == null ? _entrance : Listenable.merge([_entrance, _float!]),
      builder: (context, _) => SizedBox(
        width: maxX - minX,
        height: maxY - minY,
        child: Stack(
          clipBehavior: Clip.none,
          children: [
            for (var i = 0; i < shown.length; i++)
              _positioned(
                center: centers[i],
                radius: radii[i],
                minX: minX,
                minY: minY,
                entranceT: _entranceT(i, shown.length),
                floatOffset: _floatOffset(i, _entranceT(i, shown.length)),
                child: _Bubble(person: shown[i], size: radii[i] * 2, groupId: widget.groupId),
              ),
            if (overflow > 0)
              _positioned(
                center: centers.last,
                radius: radii.last,
                minX: minX,
                minY: minY,
                entranceT: _entranceT(shown.length, shown.length),
                floatOffset: _floatOffset(shown.length, _entranceT(shown.length, shown.length)),
                child: _OverflowBubble(count: overflow, size: radii.last * 2),
              ),
          ],
        ),
      ),
    );
  }

  /// One bubble at its packed [center]/[radius] - the [Positioned] left/top are exactly what
  /// the packer computed, untouched by animation; only the paint-layer transforms inside
  /// move, so the packing itself (what the determinism test asserts) never changes.
  Widget _positioned({
    required Offset center,
    required double radius,
    required double minX,
    required double minY,
    required double entranceT,
    required double floatOffset,
    required Widget child,
  }) {
    return Positioned(
      left: center.dx - radius - minX,
      top: center.dy - radius - minY,
      child: Transform.translate(
        offset: Offset(0, floatOffset),
        child: Transform.scale(
          scale: entranceT,
          alignment: Alignment.center,
          child: Opacity(opacity: entranceT, child: child),
        ),
      ),
    );
  }
}

const _packAngles = 16;
const _packGap = 3.0;

/// Greedily packs circles of the given radii into a cluster, largest-first: the first
/// circle sits at the origin, and each subsequent one is placed tangent to whichever
/// already-placed circle - tried at [_packAngles] angles around it, jittered by [rng] so the
/// result reads as a scattered pile rather than a ring - lands it closest to the center
/// without overlapping anything already placed.
///
/// Deterministic for a given (radii, rng) pair: the same radii list packed with a
/// `math.Random` seeded the same way always produces the same centers, which is the whole
/// point of seeding it from the recap's own id rather than leaving it unseeded (see
/// [_BubbleCluster.seed]).
List<Offset> _packCircles(List<double> radii, math.Random rng) {
  if (radii.isEmpty) return const [];
  final centers = <Offset>[Offset.zero];
  for (var i = 1; i < radii.length; i++) {
    final r = radii[i];
    Offset? best;
    var bestDist = double.infinity;
    for (var j = 0; j < centers.length; j++) {
      final dist = radii[j] + r + _packGap;
      final jitter = rng.nextDouble() * (2 * math.pi / _packAngles);
      for (var a = 0; a < _packAngles; a++) {
        final angle = (2 * math.pi * a / _packAngles) + jitter;
        final candidate = centers[j] + Offset(math.cos(angle), math.sin(angle)) * dist;
        if (_overlapsAny(candidate, r, centers, radii)) continue;
        final d = candidate.distance;
        if (d < bestDist) {
          bestDist = d;
          best = candidate;
        }
      }
    }
    // Only reachable with a pathologically large bubble count relative to _packAngles - a
    // deterministic fallback keeps the layout total (and still seeded) rather than throwing.
    if (best == null) {
      final angle = rng.nextDouble() * 2 * math.pi;
      best = Offset(math.cos(angle), math.sin(angle)) * (r + 300);
    }
    centers.add(best);
  }
  return centers;
}

bool _overlapsAny(Offset candidate, double r, List<Offset> centers, List<double> radii) {
  for (var k = 0; k < centers.length; k++) {
    if ((candidate - centers[k]).distance < radii[k] + r - 0.01) return true;
  }
  return false;
}

/// One member's bubble: their avatar (photo or initial - [UserAvatar] already handles the
/// fallback) ringed in a thin white border so it reads as a bubble against the blurred
/// backdrop, even where it overlaps a neighbour.
class _Bubble extends StatelessWidget {
  const _Bubble({required this.person, required this.size, required this.groupId});

  final RecapPerson person;
  final double size;
  final String? groupId;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: size,
      height: size,
      decoration: BoxDecoration(
        shape: BoxShape.circle,
        border: Border.all(color: Colors.white.withValues(alpha: 0.85), width: 2),
        boxShadow: const [BoxShadow(color: Colors.black45, blurRadius: 6)],
      ),
      child: ClipOval(
        child: UserAvatar(
          name: person.name,
          size: size - 4,
          mediaId: person.photoId,
          colorSeed: person.userId,
          groupId: groupId,
        ),
      ),
    );
  }
}

/// The cluster's overflow bubble: "+N" for the posters past [_BubbleCluster._cap], styled to
/// match the avatar bubbles around it.
class _OverflowBubble extends StatelessWidget {
  const _OverflowBubble({required this.count, required this.size});

  final int count;
  final double size;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: size,
      height: size,
      alignment: Alignment.center,
      decoration: BoxDecoration(
        shape: BoxShape.circle,
        color: Colors.black.withValues(alpha: 0.55),
        border: Border.all(color: Colors.white.withValues(alpha: 0.85), width: 2),
      ),
      child: Text('+$count',
          style:
              TextStyle(color: Colors.white, fontWeight: FontWeight.w800, fontSize: size * 0.32)),
    );
  }
}

/// "The Wall": the ranked collage, fridge-door style - one deck page per chunk of up to
/// [_wallCardsPerPage] cards (see RecapDeckState._buildPages), laid out as the same 2x2 grid
/// of portrait tiles that always shipped here - exactly what the founder's own screenshot
/// showed, and he never complained about how the tiles looked, only that the second row was
/// unreachable. That's a page-height problem, not a tile-layout problem: squashing the tiles
/// into a single wide-and-short row instead (an earlier version of this fix did exactly
/// that) traded an unreachable row for an unrecognisable ~1:3 sliver of every photo. The real
/// fix is _deckAspectRatio - tall enough that a 2x2 grid of these portrait tiles and its
/// padding fits inside one page with room to spare (see _deckAspectRatio's own doc comment).
///
/// No panel title ("The Wall") is rendered here (round 5) - the founder found it redundant
/// with the RECAP badge and group name already on the post card's header, and dropping it
/// bought back the vertical margin that let _deckAspectRatio shrink. The title still exists
/// on [RecapCollagePanel.title] for a server that expects to read it back unchanged; this
/// panel simply never reads it.
class _WallPanel extends StatelessWidget {
  const _WallPanel({required this.cards, required this.groupId});

  final List<RecapCard> cards;
  final String? groupId;

  @override
  Widget build(BuildContext context) {
    return DecoratedBox(
      decoration: const BoxDecoration(color: _bgSurface),
      child: Padding(
        padding: const EdgeInsets.all(10),
        child: GridView.builder(
          physics: const NeverScrollableScrollPhysics(),
          gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
            crossAxisCount: 2,
            mainAxisSpacing: 8,
            crossAxisSpacing: 8,
            childAspectRatio: 0.85,
          ),
          itemCount: cards.length,
          itemBuilder: (context, i) => _WallTile(card: cards[i], groupId: groupId),
        ),
      ),
    );
  }
}

class _WallTile extends StatelessWidget {
  const _WallTile({required this.card, required this.groupId});

  final RecapCard card;
  final String? groupId;

  /// Tapping a card that still has its photo/clip opens it full screen, the same authenticated
  /// path a feed post's own carousel uses (see post_card.dart's `_openViewer`); the viewer's
  /// own "Go to post" button (see [PhotoViewerScreen.postId]) is where a tap on the fullscreen
  /// photo can reach the original check-in. A quote card has nothing to show full screen, and
  /// a card whose media is gone (the removed-tile placeholder below) has nothing either - both
  /// go straight to the post instead, which still exists even once its photo doesn't.
  void _onTap(BuildContext context) {
    final media = card.media;
    if (media == null) {
      Navigator.of(context).push(MaterialPageRoute(
        builder: (_) => PostDetailScreen(postId: card.postId, groupId: groupId),
      ));
      return;
    }
    PhotoViewerScreen.open(context, media: [media], groupId: groupId, postId: card.postId);
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => _onTap(context),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(10),
        child: Stack(
          fit: StackFit.expand,
          children: [
            _WallTileContent(card: card, groupId: groupId),
            Positioned(
              left: 6,
              right: 6,
              top: 6,
              child: Row(
                children: [
                  UserAvatar(
                    name: card.authorName,
                    size: 20,
                    mediaId: card.authorPhotoId,
                    colorSeed: card.authorId,
                    groupId: groupId,
                  ),
                  const SizedBox(width: 5),
                  Expanded(
                    child: Text(
                      card.authorName,
                      overflow: TextOverflow.ellipsis,
                      style: const TextStyle(
                        color: Colors.white,
                        fontWeight: FontWeight.w700,
                        fontSize: 11,
                        shadows: [Shadow(color: Colors.black87, blurRadius: 4)],
                      ),
                    ),
                  ),
                ],
              ),
            ),
            if (card.rank == 1)
              const Positioned(
                top: 6,
                right: 6,
                child: Icon(Icons.star_rounded, color: Colors.amber, size: 18, shadows: [
                  Shadow(color: Colors.black54, blurRadius: 4),
                ]),
              ),
          ],
        ),
      ),
    );
  }
}

/// The tile's body: the photo/clip attachment, a quote card, or - when a photo/clip card's
/// media is missing (a deleted attachment; the payload's frozen mediaId can outlive the
/// file it named) - a tasteful "removed" placeholder rather than a broken layout.
class _WallTileContent extends StatelessWidget {
  const _WallTileContent({required this.card, required this.groupId});

  final RecapCard card;
  final String? groupId;

  @override
  Widget build(BuildContext context) {
    if (card.isQuote) {
      return Container(
        color: context.accent.withValues(alpha: 0.18),
        padding: const EdgeInsets.all(10),
        alignment: Alignment.center,
        child: Text(
          card.body,
          maxLines: 5,
          overflow: TextOverflow.ellipsis,
          textAlign: TextAlign.center,
          style: const TextStyle(color: _fgPrimary, fontWeight: FontWeight.w600, fontSize: 13),
        ),
      );
    }
    final media = card.media;
    if (media == null) {
      return Container(
        color: _bgSurfaceHover,
        alignment: Alignment.center,
        child: const Icon(Icons.image_not_supported_outlined, color: _fgMuted, size: 28),
      );
    }
    return MediaFrame(media: media, groupId: groupId);
  }
}

/// "Awards Night": the period's superlatives, one row per award.
class _AwardsPanel extends StatelessWidget {
  const _AwardsPanel({required this.panel, required this.groupId});

  final RecapAwardsPanel panel;
  final String? groupId;

  @override
  Widget build(BuildContext context) {
    return DecoratedBox(
      decoration: const BoxDecoration(color: _bgSurface),
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(panel.title,
                style:
                    const TextStyle(color: _fgPrimary, fontWeight: FontWeight.w800, fontSize: 18)),
            const SizedBox(height: 6),
            Expanded(
              child: ListView.separated(
                physics: const NeverScrollableScrollPhysics(),
                itemCount: panel.awards.length,
                separatorBuilder: (_, __) => const Divider(color: _border, height: 20),
                itemBuilder: (context, i) => _AwardRow(award: panel.awards[i], groupId: groupId),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _AwardRow extends StatelessWidget {
  const _AwardRow({required this.award, required this.groupId});

  final RecapAward award;
  final String? groupId;

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        UserAvatar(
          name: award.userName,
          size: 34,
          mediaId: award.userPhotoId,
          colorSeed: award.userId,
          groupId: groupId,
        ),
        const SizedBox(width: 10),
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(award.label,
                  style: const TextStyle(
                      color: _fgSecondary, fontWeight: FontWeight.w600, fontSize: 12)),
              Text(award.userName,
                  overflow: TextOverflow.ellipsis,
                  style: const TextStyle(
                      color: _fgPrimary, fontWeight: FontWeight.w700, fontSize: 15)),
            ],
          ),
        ),
        Text(award.value, style: const TextStyle(color: _fgMuted, fontSize: 13)),
      ],
    );
  }
}

/// Shown when a recap payload has zero panels this client recognises (every panel type in
/// it is newer than this build understands) - a plain stats summary rather than an empty
/// deck, mirroring the caption-only fallback older client generations get entirely.
class _RecapStatsFallback extends StatelessWidget {
  const _RecapStatsFallback({required this.recap});

  final RecapPayload recap;

  @override
  Widget build(BuildContext context) {
    final s = recap.stats;
    final unit = recap.cadence == 'monthly' ? 'month' : 'period';
    return Container(
      color: _bgSurface,
      padding: const EdgeInsets.symmetric(vertical: 28, horizontal: 16),
      alignment: Alignment.center,
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          const Icon(Icons.auto_awesome_outlined, color: _fgMuted, size: 28),
          const SizedBox(height: 8),
          Text('${s.posts} check-ins this $unit',
              style: const TextStyle(color: _fgPrimary, fontWeight: FontWeight.w600, fontSize: 14)),
          const SizedBox(height: 4),
          const Text('Update Check-In to see the full recap.',
              style: TextStyle(color: _fgMuted, fontSize: 12)),
        ],
      ),
    );
  }
}
