import 'dart:math' as math;
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:gal/gal.dart';

import '../../api/models.dart';
import '../../theme/accent.dart';
import '../../theme/tokens.dart';
import '../../widgets/media_frame.dart';
import '../../widgets/user_avatar.dart';

const _bgSurface = kBgSurface;
const _bgSurfaceHover = kBgSurfaceHover;
const _border = kBorder;
const _fgPrimary = kFgPrimary;
const _fgSecondary = kFgSecondary;
const _fgMuted = kFgMuted;

/// RecapDeck renders a recap post's panels as a swipeable, PageView deck: a cover page
/// (the group's own moment - see [_RecapCoverPage]) followed by whichever panels the
/// payload carries - the collage ("The Wall") in every recap generated by this server
/// version, or awards ("Awards Night") too on a deck generated by an older one still
/// sitting in the feed (Awards Night itself is retired; profile titles replaced it).
///
/// A panel type this client doesn't recognise never reaches here at all: [Post.fromJson]
/// drops it via [RecapPanel.tryParse], which is the forward-compat contract that lets a
/// v1.5+ server add new panel types without breaking this client. When that leaves zero
/// panels, the deck falls back to a plain stats summary (no cover either) rather than
/// rendering nothing.
class RecapDeck extends StatefulWidget {
  const RecapDeck({super.key, required this.recap, required this.groupId, required this.postId});

  final RecapPayload recap;
  final String? groupId;

  /// The recap post's own id - carried through to the cover for its avatar-bubble cluster,
  /// which seeds its jittered layout from it (see _BubbleCluster's doc comment).
  final int postId;

  @override
  State<RecapDeck> createState() => RecapDeckState();
}

/// Public so [PostCard] can reach [saveCurrentPage] through a [GlobalKey] - the overflow
/// menu's "Save this panel" item lives on the post card, not the deck, matching where every
/// other post's save action lives (see post_card.dart's PopupMenuButton).
class RecapDeckState extends State<RecapDeck> {
  final _controller = PageController();
  final Map<int, GlobalKey> _boundaryKeys = {};
  int _page = 0;

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  GlobalKey _keyFor(int index) => _boundaryKeys.putIfAbsent(index, () => GlobalKey());

  /// Rasterizes whichever page the deck is currently showing and saves it - what the post
  /// card's overflow-menu "Save this panel" item calls.
  Future<void> saveCurrentPage() => _savePanel(_page);

  /// Rasterizes the current panel's [RepaintBoundary] and saves it to the device gallery -
  /// the v1 "generated image" flow. Zero new dependencies: both halves already exist
  /// in-tree (photo_crop_screen.dart's capture, post_card.dart's Gal save).
  Future<void> _savePanel(int index) async {
    try {
      final boundary = _keyFor(index).currentContext!.findRenderObject() as RenderRepaintBoundary;
      final pixelRatio = (1080.0 / boundary.size.width).clamp(1.0, 4.0);
      final image = await boundary.toImage(pixelRatio: pixelRatio);
      final data = await image.toByteData(format: ui.ImageByteFormat.png);
      image.dispose();
      if (data == null) return;
      await Gal.putImageBytes(data.buffer.asUint8List());
      _snack('Saved to your photos');
    } on GalException catch (_) {
      _snack('Allow photo access to save this');
    } catch (_) {
      _snack('Could not save this panel');
    }
  }

  void _snack(String msg) {
    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(msg)));
  }

  @override
  Widget build(BuildContext context) {
    final panels = widget.recap.panels;
    if (panels.isEmpty) {
      return _RecapStatsFallback(recap: widget.recap);
    }
    // Page 0 is always the cover - a system moment, not a normal post header - with every
    // recognised panel following after it in the order the payload carries them.
    final pageCount = panels.length + 1;
    return Column(
      mainAxisSize: MainAxisSize.min,
      children: [
        AspectRatio(
          // A normal media-frame aspect (matching post_image_carousel's own default), not
          // the tall hero the cover used to render at - the deck reads as a normal post's
          // footprint now, distinguished by its accent outline, not its size.
          aspectRatio: 4 / 3,
          child: PageView.builder(
            controller: _controller,
            itemCount: pageCount,
            onPageChanged: (i) => setState(() => _page = i),
            itemBuilder: (context, index) => RepaintBoundary(
              key: _keyFor(index),
              child: index == 0
                  ? _RecapCoverPage(
                      recap: widget.recap, groupId: widget.groupId, postId: widget.postId)
                  : _RecapPanelView(panel: panels[index - 1], groupId: widget.groupId),
            ),
          ),
        ),
        // Page dots only - saving now lives in the post card's overflow menu, alongside
        // every other post's save action (see PostCard's PopupMenuButton and
        // RecapDeckState.saveCurrentPage).
        Padding(
          padding: const EdgeInsets.symmetric(vertical: 10),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              for (var i = 0; i < pageCount; i++)
                Container(
                  margin: const EdgeInsets.symmetric(horizontal: 3),
                  width: i == _page ? 16 : 6,
                  height: 6,
                  decoration: BoxDecoration(
                    color: i == _page ? context.accent : _border,
                    borderRadius: BorderRadius.circular(3),
                  ),
                ),
            ],
          ),
        ),
      ],
    );
  }
}

/// Dispatches to the right panel renderer. panel is one of the two v1 subtypes
/// ([RecapCollagePanel], [RecapAwardsPanel]) by construction - [RecapPanel.tryParse] never
/// hands back anything else - so the switch is exhaustive with no default case.
class _RecapPanelView extends StatelessWidget {
  const _RecapPanelView({required this.panel, required this.groupId});

  final RecapPanel panel;
  final String? groupId;

  @override
  Widget build(BuildContext context) => switch (panel) {
        RecapCollagePanel p => _WallPanel(panel: p, groupId: groupId),
        RecapAwardsPanel p => _AwardsPanel(panel: p, groupId: groupId),
      };
}

/// The deck's first page: a system moment, not a normal post header. A dimmed, blurred hero
/// backdrop (the Wall's #1 photo, when there is one) sits behind a pile of the period's
/// posters' avatars and the at-a-glance stats - what makes a recap post read as a group
/// artifact at a glance rather than one more check-in in the feed. The group's own name is
/// deliberately not repeated here - the post card's header already carries it (see
/// post_card.dart's group-name label next to the RECAP badge).
class _RecapCoverPage extends StatelessWidget {
  const _RecapCoverPage({required this.recap, required this.groupId, required this.postId});

  final RecapPayload recap;
  final String? groupId;

  /// The recap post's own id, threaded down for the bubble cluster's deterministic seed -
  /// see _BubbleCluster's doc comment.
  final int postId;

  /// The Wall panel's rank-1 card, when it carries a photo or clip - the "top photo" the
  /// backdrop is built from. Null for an awards-only historical deck, a text-only #1 pick,
  /// or simply no collage panel at all; the cover still renders, just without a photo.
  RecapCard? get _hero {
    for (final panel in recap.panels) {
      if (panel is RecapCollagePanel) {
        for (final card in panel.cards) {
          if (card.rank == 1 && card.media != null) return card;
        }
      }
    }
    return null;
  }

  String get _eyebrow => switch (recap.cadence) {
        'weekly' => 'WEEKLY RECAP',
        'monthly' => 'MONTHLY RECAP',
        _ => 'RECAP',
      };

  String get _statsLine {
    final s = recap.stats;
    return [
      '${s.posts} ${s.posts == 1 ? 'check-in' : 'check-ins'}',
      '${s.places} ${s.places == 1 ? 'place' : 'places'}',
      '${s.members} ${s.members == 1 ? 'member' : 'members'}',
    ].join(' · ');
  }

  @override
  Widget build(BuildContext context) {
    final accent = accentById(recap.groupColor);
    final hero = _hero;
    const textShadows = [Shadow(color: Colors.black87, blurRadius: 10)];
    return DecoratedBox(
      decoration:
          BoxDecoration(color: Color.alphaBlend(accent.base.withValues(alpha: 0.16), _bgSurface)),
      child: Stack(
        fit: StackFit.expand,
        children: [
          // A missing or failed (404) hero degrades to the plain tinted background above -
          // MediaFrame/AuthImage already render their own placeholder on a load failure, so
          // there is nothing extra to guard here.
          if (hero != null)
            ImageFiltered(
              imageFilter: ui.ImageFilter.blur(sigmaX: 20, sigmaY: 20),
              // Quieter than before (was 0.5): the backdrop is a supporting texture now,
              // not the cover's focal point - the avatar cluster below is.
              child:
                  Opacity(opacity: 0.32, child: MediaFrame(media: hero.media!, groupId: groupId)),
            ),
          DecoratedBox(
            decoration: BoxDecoration(
              gradient: LinearGradient(
                begin: Alignment.topCenter,
                end: Alignment.bottomCenter,
                colors: [
                  Colors.black.withValues(alpha: hero == null ? 0.05 : 0.35),
                  Color.alphaBlend(accent.base.withValues(alpha: 0.24), _bgSurface)
                      .withValues(alpha: 0.94),
                ],
              ),
            ),
          ),
          // The people who posted this period, piled as a cluster of avatar bubbles sized by
          // contribution - the cover's "who's in this" moment. _BubbleCluster itself renders
          // nothing (see its empty-list guard) on a payload recorded before
          // RecapPayload.people existed, which just leaves the plain backdrop above as the
          // cover's whole focal point, same as it always has.
          Align(
            alignment: const Alignment(0, -0.1),
            child: _BubbleCluster(people: recap.people, seed: postId, groupId: groupId),
          ),
          Padding(
            padding: const EdgeInsets.all(20),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.end,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                  decoration:
                      BoxDecoration(color: accent.base, borderRadius: BorderRadius.circular(9999)),
                  child: Text(_eyebrow,
                      style: TextStyle(
                          color: accent.onAccent,
                          fontWeight: FontWeight.w800,
                          fontSize: 11,
                          letterSpacing: 1.1)),
                ),
                const SizedBox(height: 10),
                // The period label carries the cover's headline weight now that the group
                // name (already in the post card's header) isn't repeated here.
                Text(recap.periodLabel,
                    style: const TextStyle(
                        color: Colors.white,
                        fontWeight: FontWeight.w700,
                        fontSize: 16,
                        shadows: textShadows)),
                const SizedBox(height: 6),
                Text(_statsLine,
                    style: TextStyle(
                        color: Colors.white.withValues(alpha: 0.95),
                        fontWeight: FontWeight.w600,
                        fontSize: 13,
                        shadows: textShadows)),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

/// A pile of avatar bubbles for the people who posted this period, sized by contribution
/// (the biggest poster gets the biggest bubble) and packed into a jittered but deterministic
/// cluster - never a rigid grid, but the same recap always packs identically (see
/// [_packCircles]'s doc comment for why).
class _BubbleCluster extends StatelessWidget {
  const _BubbleCluster({required this.people, required this.seed, required this.groupId});

  final List<RecapPerson> people;

  /// Seeds the layout's jitter - the recap post's own id (see _RecapCoverPage.postId), so
  /// the same recap always packs identically across rebuilds and app launches, while a
  /// different recap (a different id) packs differently. Deliberately never an unseeded
  /// `math.Random()`: that would reshuffle the pile on every single rebuild instead of only
  /// when the recap itself changes.
  final int seed;
  final String? groupId;

  /// At most this many bubbles render as avatars; anyone past it is folded into a single
  /// "+N" bubble. [people] is already ordered by contribution desc (server-side), so the
  /// cap always drops the least active posters, not an arbitrary subset.
  static const _cap = 7;
  static const _minSize = 30.0;
  static const _maxSize = 62.0;

  @override
  Widget build(BuildContext context) {
    if (people.isEmpty) return const SizedBox.shrink();
    final shown = people.take(_cap).toList();
    final overflow = people.length - shown.length;
    final maxPosts = shown.first.posts <= 0 ? 1 : shown.first.posts;

    final radii = <double>[
      for (final p in shown) _sizeFor(p.posts, maxPosts) / 2,
      if (overflow > 0) _minSize / 2,
    ];
    final centers = _packCircles(radii, math.Random(seed));

    var minX = double.infinity, minY = double.infinity;
    var maxX = -double.infinity, maxY = -double.infinity;
    for (var i = 0; i < centers.length; i++) {
      minX = math.min(minX, centers[i].dx - radii[i]);
      maxX = math.max(maxX, centers[i].dx + radii[i]);
      minY = math.min(minY, centers[i].dy - radii[i]);
      maxY = math.max(maxY, centers[i].dy + radii[i]);
    }

    return SizedBox(
      width: maxX - minX,
      height: maxY - minY,
      child: Stack(
        clipBehavior: Clip.none,
        children: [
          for (var i = 0; i < shown.length; i++)
            Positioned(
              left: centers[i].dx - radii[i] - minX,
              top: centers[i].dy - radii[i] - minY,
              child: _Bubble(person: shown[i], size: radii[i] * 2, groupId: groupId),
            ),
          if (overflow > 0)
            Positioned(
              left: centers.last.dx - radii.last - minX,
              top: centers.last.dy - radii.last - minY,
              child: _OverflowBubble(count: overflow, size: radii.last * 2),
            ),
        ],
      ),
    );
  }

  /// Linear interpolation from the smallest to the largest bubble size, by this member's
  /// post count as a share of the top contributor's - the biggest poster gets the biggest
  /// bubble, everyone else scales down from there.
  static double _sizeFor(int posts, int maxPosts) {
    final t = (posts / maxPosts).clamp(0.0, 1.0);
    return _minSize + (_maxSize - _minSize) * t;
  }
}

const _packAngles = 16;
const _packGap = 3.0;

/// Greedily packs circles of the given radii into a cluster, largest-first: the first
/// circle sits at the origin, and each subsequent one is placed tangent to whichever
/// already-placed circle - tried at [_packAngles] angles around it, jittered by [rng] so the
/// result reads as a scattered pile rather than a ring - lands it closest to the center
/// without overlapping anything already placed.
///
/// Deterministic for a given (radii, rng) pair: the same radii list packed with a
/// `math.Random` seeded the same way always produces the same centers, which is the whole
/// point of seeding it from the recap's own id rather than leaving it unseeded (see
/// [_BubbleCluster.seed]).
List<Offset> _packCircles(List<double> radii, math.Random rng) {
  if (radii.isEmpty) return const [];
  final centers = <Offset>[Offset.zero];
  for (var i = 1; i < radii.length; i++) {
    final r = radii[i];
    Offset? best;
    var bestDist = double.infinity;
    for (var j = 0; j < centers.length; j++) {
      final dist = radii[j] + r + _packGap;
      final jitter = rng.nextDouble() * (2 * math.pi / _packAngles);
      for (var a = 0; a < _packAngles; a++) {
        final angle = (2 * math.pi * a / _packAngles) + jitter;
        final candidate = centers[j] + Offset(math.cos(angle), math.sin(angle)) * dist;
        if (_overlapsAny(candidate, r, centers, radii)) continue;
        final d = candidate.distance;
        if (d < bestDist) {
          bestDist = d;
          best = candidate;
        }
      }
    }
    // Only reachable with a pathologically large bubble count relative to _packAngles - a
    // deterministic fallback keeps the layout total (and still seeded) rather than throwing.
    if (best == null) {
      final angle = rng.nextDouble() * 2 * math.pi;
      best = Offset(math.cos(angle), math.sin(angle)) * (r + 300);
    }
    centers.add(best);
  }
  return centers;
}

bool _overlapsAny(Offset candidate, double r, List<Offset> centers, List<double> radii) {
  for (var k = 0; k < centers.length; k++) {
    if ((candidate - centers[k]).distance < radii[k] + r - 0.01) return true;
  }
  return false;
}

/// One member's bubble: their avatar (photo or initial - [UserAvatar] already handles the
/// fallback) ringed in a thin white border so it reads as a bubble against the blurred
/// backdrop, even where it overlaps a neighbour.
class _Bubble extends StatelessWidget {
  const _Bubble({required this.person, required this.size, required this.groupId});

  final RecapPerson person;
  final double size;
  final String? groupId;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: size,
      height: size,
      decoration: BoxDecoration(
        shape: BoxShape.circle,
        border: Border.all(color: Colors.white.withValues(alpha: 0.85), width: 2),
        boxShadow: const [BoxShadow(color: Colors.black45, blurRadius: 6)],
      ),
      child: ClipOval(
        child: UserAvatar(
          name: person.name,
          size: size - 4,
          mediaId: person.photoId,
          colorSeed: person.userId,
          groupId: groupId,
        ),
      ),
    );
  }
}

/// The cluster's overflow bubble: "+N" for the posters past [_BubbleCluster._cap], styled to
/// match the avatar bubbles around it.
class _OverflowBubble extends StatelessWidget {
  const _OverflowBubble({required this.count, required this.size});

  final int count;
  final double size;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: size,
      height: size,
      alignment: Alignment.center,
      decoration: BoxDecoration(
        shape: BoxShape.circle,
        color: Colors.black.withValues(alpha: 0.55),
        border: Border.all(color: Colors.white.withValues(alpha: 0.85), width: 2),
      ),
      child: Text('+$count',
          style:
              TextStyle(color: Colors.white, fontWeight: FontWeight.w800, fontSize: size * 0.32)),
    );
  }
}

/// "The Wall": the ranked collage, fridge-door style - a grid of tiles each carrying the
/// author's name (and, for a text-only guaranteed slot, a quote card instead of a photo).
class _WallPanel extends StatelessWidget {
  const _WallPanel({required this.panel, required this.groupId});

  final RecapCollagePanel panel;
  final String? groupId;

  @override
  Widget build(BuildContext context) {
    return DecoratedBox(
      decoration: const BoxDecoration(color: _bgSurface),
      child: Padding(
        padding: const EdgeInsets.all(10),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 4, vertical: 6),
              child: Text(panel.title,
                  style: const TextStyle(
                      color: _fgPrimary, fontWeight: FontWeight.w800, fontSize: 18)),
            ),
            Expanded(
              child: GridView.builder(
                physics: const NeverScrollableScrollPhysics(),
                gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                  crossAxisCount: 2,
                  mainAxisSpacing: 8,
                  crossAxisSpacing: 8,
                  childAspectRatio: 0.85,
                ),
                itemCount: panel.cards.length,
                itemBuilder: (context, i) => _WallTile(card: panel.cards[i], groupId: groupId),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _WallTile extends StatelessWidget {
  const _WallTile({required this.card, required this.groupId});

  final RecapCard card;
  final String? groupId;

  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.circular(10),
      child: Stack(
        fit: StackFit.expand,
        children: [
          _WallTileContent(card: card, groupId: groupId),
          Positioned(
            left: 6,
            right: 6,
            top: 6,
            child: Row(
              children: [
                UserAvatar(
                  name: card.authorName,
                  size: 20,
                  mediaId: card.authorPhotoId,
                  colorSeed: card.authorId,
                  groupId: groupId,
                ),
                const SizedBox(width: 5),
                Expanded(
                  child: Text(
                    card.authorName,
                    overflow: TextOverflow.ellipsis,
                    style: const TextStyle(
                      color: Colors.white,
                      fontWeight: FontWeight.w700,
                      fontSize: 11,
                      shadows: [Shadow(color: Colors.black87, blurRadius: 4)],
                    ),
                  ),
                ),
              ],
            ),
          ),
          if (card.rank == 1)
            const Positioned(
              top: 6,
              right: 6,
              child: Icon(Icons.star_rounded, color: Colors.amber, size: 18, shadows: [
                Shadow(color: Colors.black54, blurRadius: 4),
              ]),
            ),
        ],
      ),
    );
  }
}

/// The tile's body: the photo/clip attachment, a quote card, or - when a photo/clip card's
/// media is missing (a deleted attachment; the payload's frozen mediaId can outlive the
/// file it named) - a tasteful "removed" placeholder rather than a broken layout.
class _WallTileContent extends StatelessWidget {
  const _WallTileContent({required this.card, required this.groupId});

  final RecapCard card;
  final String? groupId;

  @override
  Widget build(BuildContext context) {
    if (card.isQuote) {
      return Container(
        color: context.accent.withValues(alpha: 0.18),
        padding: const EdgeInsets.all(10),
        alignment: Alignment.center,
        child: Text(
          card.body,
          maxLines: 5,
          overflow: TextOverflow.ellipsis,
          textAlign: TextAlign.center,
          style: const TextStyle(color: _fgPrimary, fontWeight: FontWeight.w600, fontSize: 13),
        ),
      );
    }
    final media = card.media;
    if (media == null) {
      return Container(
        color: _bgSurfaceHover,
        alignment: Alignment.center,
        child: const Icon(Icons.image_not_supported_outlined, color: _fgMuted, size: 28),
      );
    }
    return MediaFrame(media: media, groupId: groupId);
  }
}

/// "Awards Night": the period's superlatives, one row per award.
class _AwardsPanel extends StatelessWidget {
  const _AwardsPanel({required this.panel, required this.groupId});

  final RecapAwardsPanel panel;
  final String? groupId;

  @override
  Widget build(BuildContext context) {
    return DecoratedBox(
      decoration: const BoxDecoration(color: _bgSurface),
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(panel.title,
                style:
                    const TextStyle(color: _fgPrimary, fontWeight: FontWeight.w800, fontSize: 18)),
            const SizedBox(height: 6),
            Expanded(
              child: ListView.separated(
                physics: const NeverScrollableScrollPhysics(),
                itemCount: panel.awards.length,
                separatorBuilder: (_, __) => const Divider(color: _border, height: 20),
                itemBuilder: (context, i) => _AwardRow(award: panel.awards[i], groupId: groupId),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _AwardRow extends StatelessWidget {
  const _AwardRow({required this.award, required this.groupId});

  final RecapAward award;
  final String? groupId;

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        UserAvatar(
          name: award.userName,
          size: 34,
          mediaId: award.userPhotoId,
          colorSeed: award.userId,
          groupId: groupId,
        ),
        const SizedBox(width: 10),
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(award.label,
                  style: const TextStyle(
                      color: _fgSecondary, fontWeight: FontWeight.w600, fontSize: 12)),
              Text(award.userName,
                  overflow: TextOverflow.ellipsis,
                  style: const TextStyle(
                      color: _fgPrimary, fontWeight: FontWeight.w700, fontSize: 15)),
            ],
          ),
        ),
        Text(award.value, style: const TextStyle(color: _fgMuted, fontSize: 13)),
      ],
    );
  }
}

/// Shown when a recap payload has zero panels this client recognises (every panel type in
/// it is newer than this build understands) - a plain stats summary rather than an empty
/// deck, mirroring the caption-only fallback older client generations get entirely.
class _RecapStatsFallback extends StatelessWidget {
  const _RecapStatsFallback({required this.recap});

  final RecapPayload recap;

  @override
  Widget build(BuildContext context) {
    final s = recap.stats;
    final unit = recap.cadence == 'monthly' ? 'month' : 'period';
    return Container(
      color: _bgSurface,
      padding: const EdgeInsets.symmetric(vertical: 28, horizontal: 16),
      alignment: Alignment.center,
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          const Icon(Icons.auto_awesome_outlined, color: _fgMuted, size: 28),
          const SizedBox(height: 8),
          Text('${s.posts} check-ins this $unit',
              style: const TextStyle(color: _fgPrimary, fontWeight: FontWeight.w600, fontSize: 14)),
          const SizedBox(height: 4),
          const Text('Update Check-In to see the full recap.',
              style: TextStyle(color: _fgMuted, fontSize: 12)),
        ],
      ),
    );
  }
}
