#!/usr/bin/env bash
# gen-stack.sh — render the multi-group deployment from the group registry.
#
# Reads groups/*.env (one file per friend group; see groups/example.env.sample) and
# writes, next to the hand-written single-group files:
#
#   docker-compose.generated.yml   shared db/caddy/backups + one server-<slug> per group
#   Caddyfile.generated            one HTTPS site block per group subdomain
#   caddy-static/<slug>/join.html  the invite landing page for each group
#   caddy-static/shared/           apple-app-site-association + assetlinks.json
#
# The original group (the bare $CHECKIN_DOMAIN, database "checkin", volume
# "media_data") is always rendered as service server-main, so an existing
# single-group install keeps its data with zero migration.
#
# Secrets are NOT baked in: the generated compose file uses the same ${VAR}
# interpolation from .env as the hand-written one. Run the stack with:
#
#   docker compose -f docker-compose.generated.yml up -d
#
# Optional .env keys used here (read only to render static files):
#   ANDROID_CERT_SHA256   Android app-signing cert fingerprint for assetlinks.json

set -euo pipefail

cd "$(dirname "$0")/.."

COMPOSE_OUT=docker-compose.generated.yml
CADDY_OUT=Caddyfile.generated
STATIC_DIR=caddy-static

APPLE_TEAM_ID="76S78SUWVM"
BUNDLE_ID="top.npcserver.checkin"

# ---- read the registry -------------------------------------------------------

slugs=()
declare -A display_names debug_tokens

for f in groups/*.env; do
  [ -e "$f" ] || continue
  # shellcheck disable=SC1090
  SLUG='' DISPLAY_NAME='' CHECKIN_DEBUG_TOKEN=''
  source "$f"
  if [ -z "$SLUG" ]; then
    echo "error: $f has no SLUG" >&2
    exit 1
  fi
  if ! [[ "$SLUG" =~ ^[a-z0-9][a-z0-9-]*$ ]]; then
    echo "error: $f: slug '$SLUG' must be lowercase letters, digits, hyphens" >&2
    exit 1
  fi
  if [ "$SLUG" = "main" ]; then
    echo "error: $f: slug 'main' is reserved for the original group" >&2
    exit 1
  fi
  slugs+=("$SLUG")
  display_names[$SLUG]="${DISPLAY_NAME:-$SLUG}"
  debug_tokens[$SLUG]="${CHECKIN_DEBUG_TOKEN:-}"
done

# Fail on duplicate slugs (two files claiming the same subdomain/database).
if [ "${#slugs[@]}" -gt 0 ]; then
  dupes=$(printf '%s\n' "${slugs[@]}" | sort | uniq -d)
  if [ -n "$dupes" ]; then
    echo "error: duplicate slug(s) in groups/: $dupes" >&2
    exit 1
  fi
fi

# Optional values read from .env only to render static files (secrets stay out of the
# generated compose file, which interpolates ${VAR} at `docker compose` time).
android_sha=""
main_name=""
if [ -f .env ]; then
  android_sha=$(sed -n 's/^ANDROID_CERT_SHA256=//p' .env | tail -1)
  main_name=$(sed -n 's/^CHECKIN_SERVER_NAME=//p' .env | tail -1 | tr -d '"')
fi

# ---- one server service ------------------------------------------------------

# emit_server <service> <database> <volume> <server-name-yaml> <public-url> <debug-token-yaml>
# server-name-yaml / debug-token-yaml are pre-quoted YAML scalars so the caller controls
# whether the value is a literal or a ${VAR} passthrough.
emit_server() {
  local svc="$1" db="$2" vol="$3" name="$4" url="$5" token="$6"
  cat <<EOF
  $svc:
    image: \${CHECKIN_IMAGE:-ghcr.io/nc1107/check-in:latest}
    restart: unless-stopped
    networks:
      - frontend
      - backend
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      # Distroless has no shell/curl, so the binary probes itself.
      test: ["CMD", "/app/server", "-healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    environment:
      CHECKIN_HTTP_ADDR: ":8080"
      CHECKIN_DATABASE_URL: "postgres://\${POSTGRES_USER:-checkin}:\${POSTGRES_PASSWORD}@db:5432/${db}?sslmode=disable"
      CHECKIN_MEDIA_DIR: "/data/media"
      CHECKIN_SERVER_NAME: ${name}
      CHECKIN_PUBLIC_URL: "${url}"
      CHECKIN_DEBUG_TOKEN: ${token}
      CHECKIN_FCM_CREDENTIALS_FILE: \${CHECKIN_FCM_CREDENTIALS_FILE:-}
    volumes:
      - ${vol}:/data/media
      - \${CHECKIN_FCM_CREDENTIALS_HOST:-/dev/null}:/run/secrets/fcm-service-account.json:ro
    deploy:
      resources:
        limits:
          # Image uploads briefly decode a full-resolution photo in memory; 512M leaves
          # headroom (256M was OOM-killed mid-upload).
          memory: 512M

EOF
}

# ---- docker-compose.generated.yml --------------------------------------------

# db-backup dumps every database; media-backup archives every media volume.
all_dbs='${POSTGRES_DB:-checkin}'
for s in "${slugs[@]}"; do all_dbs+=",checkin_${s}"; done

{
  cat <<'EOF'
# GENERATED by scripts/gen-stack.sh — DO NOT EDIT BY HAND.
# Re-render with: ./scripts/gen-stack.sh   (source of truth: groups/*.env)
#
# Multi-group Check-In stack: one PostgreSQL, one Caddy, and one app container per
# friend group, each with its own database, media volume, and subdomain. Bring it up:
#   docker compose -f docker-compose.generated.yml up -d

networks:
  # caddy reaches the servers but has no route to db.
  frontend:
  # servers reach db but are not exposed directly to caddy's external net.
  backend:

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    networks:
      - backend
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-checkin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?set POSTGRES_PASSWORD in .env}
      POSTGRES_DB: ${POSTGRES_DB:-checkin}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-checkin}"]
      interval: 5s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 512M

EOF

  # The original group. Uses the pre-multi-group database/volume names and the bare
  # domain, so existing installs keep their data.
  emit_server server-main '${POSTGRES_DB:-checkin}' media_data \
    '${CHECKIN_SERVER_NAME:-Check-In}' 'https://${CHECKIN_DOMAIN}' '${CHECKIN_DEBUG_TOKEN:-}'

  for s in "${slugs[@]}"; do
    emit_server "server-$s" "checkin_$s" "media_$s" \
      "\"${display_names[$s]}\"" "https://$s.\${CHECKIN_DOMAIN}" "\"${debug_tokens[$s]}\""
  done

  cat <<'EOF'
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    networks:
      - frontend
    depends_on:
      - server-main
    ports:
      - "80:80"
      - "443:443"
    environment:
      CHECKIN_DOMAIN: ${CHECKIN_DOMAIN:?set CHECKIN_DOMAIN in .env}
    volumes:
      - ./Caddyfile.generated:/etc/caddy/Caddyfile:ro
      - ./caddy-static:/srv/checkin-static:ro
      - caddy_data:/data
      - caddy_config:/config
    deploy:
      resources:
        limits:
          memory: 128M

  # --- Backups (write to ./backups on the host so they're easy to find & copy off-box) ---

  # Daily, consistent pg_dump of EVERY group database, with rotation. Restore one:
  #   gunzip -c ./backups/db/last/checkin_<slug>-<ts>.sql.gz | \
  #     docker compose -f docker-compose.generated.yml exec -T db psql -U checkin -d checkin_<slug>
  db-backup:
    image: prodrigestivill/postgres-backup-local:16
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_HOST: db
EOF
  printf '      POSTGRES_DB: "%s"\n' "$all_dbs"
  cat <<'EOF'
      POSTGRES_USER: ${POSTGRES_USER:-checkin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SCHEDULE: "@daily"
      BACKUP_KEEP_DAYS: "7"
      BACKUP_KEEP_WEEKS: "4"
      BACKUP_KEEP_MONTHS: "6"
    volumes:
      - ./backups/db:/backups
    deploy:
      resources:
        limits:
          memory: 128M

  # Nightly tar.gz of every group's media volume, kept 30 days. Restore: extract a
  # ./backups/media/*.tar.gz back into the matching media volume.
  media-backup:
    image: offen/docker-volume-backup:v2
    restart: unless-stopped
    environment:
      BACKUP_CRON_EXPRESSION: "0 3 * * *"
      BACKUP_FILENAME: "media-%Y-%m-%dT%H-%M-%S.tar.gz"
      BACKUP_RETENTION_DAYS: "30"
    volumes:
      - media_data:/backup/media:ro
EOF
  for s in "${slugs[@]}"; do
    printf '      - media_%s:/backup/media-%s:ro\n' "$s" "$s"
  done
  cat <<'EOF'
      - ./backups/media:/archive
    deploy:
      resources:
        limits:
          memory: 128M

volumes:
  db_data:
  media_data:
EOF
  for s in "${slugs[@]}"; do
    printf '  media_%s:\n' "$s"
  done
  cat <<'EOF'
  caddy_data:
  caddy_config:
EOF
} > "$COMPOSE_OUT"

# ---- Caddyfile.generated ------------------------------------------------------

# emit_site <host> <upstream-service> <slug-for-static>
emit_site() {
  local host="$1" svc="$2" slug="$3"
  cat <<EOF
${host} {
	import checkin_common

	# Invite landing page: https://${host}/join
	handle /join {
		root * /srv/checkin-static/${slug}
		rewrite * /join.html
		file_server
	}

	# iOS Universal Links / Android App Links association files.
	handle /.well-known/apple-app-site-association {
		root * /srv/checkin-static/shared
		rewrite * /apple-app-site-association
		header Content-Type application/json
		file_server
	}
	handle /.well-known/assetlinks.json {
		root * /srv/checkin-static/shared
		rewrite * /assetlinks.json
		header Content-Type application/json
		file_server
	}

	handle {
		reverse_proxy ${svc}:8080
	}
}

EOF
}

{
  cat <<'EOF'
# GENERATED by scripts/gen-stack.sh — DO NOT EDIT BY HAND.
# Re-render with: ./scripts/gen-stack.sh   (source of truth: groups/*.env)
#
# One HTTPS site per group. Caddy provisions + renews a Let's Encrypt certificate for
# every site block automatically (HTTP-01, no DNS plugin needed). Point each group's
# subdomain (or a wildcard *.{$CHECKIN_DOMAIN} record) at this host.

# Shared per-site config, identical to the single-group Caddyfile.
(checkin_common) {
	# Compress text payloads (JSON, HTML). Caddy skips already-compressed types
	# like image/jpeg and image/png automatically.
	encode zstd gzip

	# Security headers at the edge (server also sets these, belt-and-suspenders).
	header {
		# Pin HTTPS for a year so a network attacker can't SSL-strip the web/PWA client.
		Strict-Transport-Security "max-age=31536000; includeSubDomains"
		X-Content-Type-Options "nosniff"
		X-Frame-Options "DENY"
		Referrer-Policy "no-referrer"
		Permissions-Policy "geolocation=(), camera=(), microphone=()"
		-Server
	}

	# Larger body limit so image uploads pass through.
	request_body {
		max_size 15MB
	}
}

EOF
  emit_site '{$CHECKIN_DOMAIN}' server-main main
  for s in "${slugs[@]}"; do
    emit_site "$s.{\$CHECKIN_DOMAIN}" "server-$s" "$s"
  done
} > "$CADDY_OUT"

# ---- static assets: /join landing + association files -------------------------

mkdir -p "$STATIC_DIR/shared"

# Apple App Site Association: lets iOS open https://<group>/join directly in the app.
cat > "$STATIC_DIR/shared/apple-app-site-association" <<EOF
{
  "applinks": {
    "apps": [],
    "details": [
      {
        "appIDs": ["${APPLE_TEAM_ID}.${BUNDLE_ID}"],
        "components": [{ "/": "/join" }]
      }
    ]
  }
}
EOF

# Android App Links. Needs the app-signing cert SHA-256 (Play Console → App integrity);
# set ANDROID_CERT_SHA256 in .env and re-run, or the file ships with a placeholder.
cat > "$STATIC_DIR/shared/assetlinks.json" <<EOF
[
  {
    "relation": ["delegate_permission/common.handle_all_urls"],
    "target": {
      "namespace": "android_app",
      "package_name": "${BUNDLE_ID}",
      "sha256_cert_fingerprints": ["${android_sha:-REPLACE_WITH_PLAY_APP_SIGNING_SHA256}"]
    }
  }
]
EOF

# emit_join <slug> <display-name> <host-expr-comment>
emit_join() {
  local slug="$1" name="$2"
  mkdir -p "$STATIC_DIR/$slug"
  cat > "$STATIC_DIR/$slug/join.html" <<EOF
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Join ${name} on Check-In</title>
<style>
  body { margin: 0; font-family: -apple-system, "Segoe UI", Roboto, sans-serif;
         background: #101014; color: #ececf1; display: grid; min-height: 100vh;
         place-items: center; text-align: center; }
  main { padding: 32px 24px; max-width: 420px; }
  h1 { font-size: 24px; margin: 0 0 10px; }
  p  { color: #a2a2ad; font-size: 15px; line-height: 1.55; margin: 0 0 22px; }
  a.btn { display: inline-block; background: #5557e0; color: #fff; text-decoration: none;
          font-weight: 700; padding: 13px 26px; border-radius: 12px; }
  .hint { margin-top: 20px; font-size: 13px; color: #6f6f7a; }
  code { color: #a2a2ad; }
</style>
</head>
<body>
<main>
  <h1>You&rsquo;ve been invited to ${name}</h1>
  <p>${name} shares private check-ins on its own Check-In server. Open this invite in
     the app to join &mdash; your phone number must be on the group&rsquo;s invite list.</p>
  <a class="btn" href="checkin://join?server=https%3A%2F%2F__HOST__">Open in Check-In</a>
  <p class="hint">Don&rsquo;t have the app yet? Install <strong>Check-In</strong> from the
     App&nbsp;Store or Google&nbsp;Play, then tap &ldquo;Add group&rdquo; and enter
     <code>__HOST__</code>.</p>
</main>
<script>
  // The page is served from the group's own subdomain, so the invite target is simply
  // where we are. Rewrites the deep link + hint to this host.
  var host = location.host;
  document.querySelector('a.btn').href =
    'checkin://join?server=' + encodeURIComponent('https://' + host);
  document.querySelector('code').textContent = host;
</script>
</body>
</html>
EOF
}

emit_join main "${main_name:-your group}"
for s in "${slugs[@]}"; do
  emit_join "$s" "${display_names[$s]}"
done

echo "rendered: $COMPOSE_OUT, $CADDY_OUT, $STATIC_DIR/ (groups: main${slugs[*]:+ ${slugs[*]}})"
