#!/usr/bin/env bash
# gen-stack.sh — render the multi-group deployment from the group registry.
#
# Reads groups/*.env (one file per friend group; see groups/example.env.sample) and
# writes, next to the hand-written single-group files:
#
#   docker-compose.generated.yml   shared db/caddy/backups + one server-<slug> per group
#   Caddyfile.generated            one HTTPS site block per group subdomain
#
# Each group's invite page is served by its own server at /join, so there is nothing
# static to render.
#
# The original group (the bare $CHECKIN_DOMAIN, database "checkin", volume
# "media_data") is always rendered as service server-main, so an existing
# single-group install keeps its data with zero migration.
#
# Secrets are NOT baked in: the generated compose file uses the same ${VAR}
# interpolation from .env as the hand-written one. Run the stack with:
#
#   docker compose -f docker-compose.generated.yml up -d

set -euo pipefail

cd "$(dirname "$0")/.."

COMPOSE_OUT=docker-compose.generated.yml
CADDY_OUT=Caddyfile.generated

# ---- read the registry -------------------------------------------------------

slugs=()
declare -A display_names debug_tokens

for f in groups/*.env; do
  [ -e "$f" ] || continue
  # shellcheck disable=SC1090
  SLUG='' DISPLAY_NAME='' CHECKIN_DEBUG_TOKEN=''
  source "$f"
  if [ -z "$SLUG" ]; then
    echo "error: $f has no SLUG" >&2
    exit 1
  fi
  if ! [[ "$SLUG" =~ ^[a-z0-9][a-z0-9-]*$ ]]; then
    echo "error: $f: slug '$SLUG' must be lowercase letters, digits, hyphens" >&2
    exit 1
  fi
  if [ "$SLUG" = "main" ]; then
    echo "error: $f: slug 'main' is reserved for the original group" >&2
    exit 1
  fi
  slugs+=("$SLUG")
  display_names[$SLUG]="${DISPLAY_NAME:-$SLUG}"
  debug_tokens[$SLUG]="${CHECKIN_DEBUG_TOKEN:-}"
done

# Fail on duplicate slugs (two files claiming the same subdomain/database).
if [ "${#slugs[@]}" -gt 0 ]; then
  dupes=$(printf '%s\n' "${slugs[@]}" | sort | uniq -d)
  if [ -n "$dupes" ]; then
    echo "error: duplicate slug(s) in groups/: $dupes" >&2
    exit 1
  fi
fi

# ---- one server service ------------------------------------------------------

# emit_server <service> <database> <volume> <server-name-yaml> <public-url> <debug-token-yaml>
# server-name-yaml / debug-token-yaml are pre-quoted YAML scalars so the caller controls
# whether the value is a literal or a ${VAR} passthrough.
emit_server() {
  local svc="$1" db="$2" vol="$3" name="$4" url="$5" token="$6"
  cat <<EOF
  $svc:
    image: \${CHECKIN_IMAGE:-ghcr.io/nc1107/check-in:latest}
    restart: unless-stopped
    networks:
      - frontend
      - backend
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      # Distroless has no shell/curl, so the binary probes itself.
      test: ["CMD", "/app/server", "-healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    environment:
      CHECKIN_HTTP_ADDR: ":8080"
      CHECKIN_DATABASE_URL: "postgres://\${POSTGRES_USER:-checkin}:\${POSTGRES_PASSWORD}@db:5432/${db}?sslmode=disable"
      CHECKIN_MEDIA_DIR: "/data/media"
      CHECKIN_SERVER_NAME: ${name}
      CHECKIN_PUBLIC_URL: "${url}"
      CHECKIN_DEBUG_TOKEN: ${token}
      CHECKIN_FCM_CREDENTIALS_FILE: \${CHECKIN_FCM_CREDENTIALS_FILE:-}
    volumes:
      - ${vol}:/data/media
      - \${CHECKIN_FCM_CREDENTIALS_HOST:-/dev/null}:/run/secrets/fcm-service-account.json:ro
    deploy:
      resources:
        limits:
          # Image uploads briefly decode a full-resolution photo in memory; 512M leaves
          # headroom (256M was OOM-killed mid-upload).
          memory: 512M

EOF
}

# ---- docker-compose.generated.yml --------------------------------------------

# db-backup dumps every database; media-backup archives every media volume.
all_dbs='${POSTGRES_DB:-checkin}'
for s in "${slugs[@]}"; do all_dbs+=",checkin_${s}"; done

{
  cat <<'EOF'
# GENERATED by scripts/gen-stack.sh — DO NOT EDIT BY HAND.
# Re-render with: ./scripts/gen-stack.sh   (source of truth: groups/*.env)
#
# Multi-group Check-In stack: one PostgreSQL, one Caddy, and one app container per
# friend group, each with its own database, media volume, and subdomain. Bring it up:
#   docker compose -f docker-compose.generated.yml up -d

networks:
  # caddy reaches the servers but has no route to db.
  frontend:
  # servers reach db but are not exposed directly to caddy's external net.
  backend:

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    networks:
      - backend
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-checkin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?set POSTGRES_PASSWORD in .env}
      POSTGRES_DB: ${POSTGRES_DB:-checkin}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-checkin}"]
      interval: 5s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 512M

EOF

  # The original group. Uses the pre-multi-group database/volume names and the bare
  # domain, so existing installs keep their data.
  emit_server server-main '${POSTGRES_DB:-checkin}' media_data \
    '${CHECKIN_SERVER_NAME:-Check-In}' 'https://${CHECKIN_DOMAIN}' '${CHECKIN_DEBUG_TOKEN:-}'

  for s in "${slugs[@]}"; do
    emit_server "server-$s" "checkin_$s" "media_$s" \
      "\"${display_names[$s]}\"" "https://$s.\${CHECKIN_DOMAIN}" "\"${debug_tokens[$s]}\""
  done

  cat <<'EOF'
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    networks:
      - frontend
    depends_on:
      - server-main
    ports:
      - "80:80"
      - "443:443"
    environment:
      CHECKIN_DOMAIN: ${CHECKIN_DOMAIN:?set CHECKIN_DOMAIN in .env}
    volumes:
      - ./Caddyfile.generated:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    deploy:
      resources:
        limits:
          memory: 128M

  # --- Backups (write to ./backups on the host so they're easy to find & copy off-box) ---

  # Daily, consistent pg_dump of EVERY group database, with rotation. Restore one:
  #   gunzip -c ./backups/db/last/checkin_<slug>-<ts>.sql.gz | \
  #     docker compose -f docker-compose.generated.yml exec -T db psql -U checkin -d checkin_<slug>
  db-backup:
    image: prodrigestivill/postgres-backup-local:16
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_HOST: db
EOF
  printf '      POSTGRES_DB: "%s"\n' "$all_dbs"
  cat <<'EOF'
      POSTGRES_USER: ${POSTGRES_USER:-checkin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SCHEDULE: "@daily"
      BACKUP_KEEP_DAYS: "7"
      BACKUP_KEEP_WEEKS: "4"
      BACKUP_KEEP_MONTHS: "6"
    volumes:
      - ./backups/db:/backups
    deploy:
      resources:
        limits:
          memory: 128M

  # Nightly tar.gz of every group's media volume, kept 30 days. Restore: extract a
  # ./backups/media/*.tar.gz back into the matching media volume.
  media-backup:
    image: offen/docker-volume-backup:v2
    restart: unless-stopped
    environment:
      BACKUP_CRON_EXPRESSION: "0 3 * * *"
      BACKUP_FILENAME: "media-%Y-%m-%dT%H-%M-%S.tar.gz"
      BACKUP_RETENTION_DAYS: "30"
    volumes:
      - media_data:/backup/media:ro
EOF
  for s in "${slugs[@]}"; do
    printf '      - media_%s:/backup/media-%s:ro\n' "$s" "$s"
  done
  cat <<'EOF'
      - ./backups/media:/archive
    deploy:
      resources:
        limits:
          memory: 128M

volumes:
  db_data:
  media_data:
EOF
  for s in "${slugs[@]}"; do
    printf '  media_%s:\n' "$s"
  done
  cat <<'EOF'
  caddy_data:
  caddy_config:
EOF
} > "$COMPOSE_OUT"

# ---- Caddyfile.generated ------------------------------------------------------

# emit_site <host> <upstream-service>
emit_site() {
  local host="$1" svc="$2"
  cat <<EOF
${host} {
	import checkin_common

	reverse_proxy ${svc}:8080
}

EOF
}

{
  cat <<'EOF'
# GENERATED by scripts/gen-stack.sh — DO NOT EDIT BY HAND.
# Re-render with: ./scripts/gen-stack.sh   (source of truth: groups/*.env)
#
# One HTTPS site per group. Caddy provisions + renews a Let's Encrypt certificate for
# every site block automatically (HTTP-01, no DNS plugin needed). Point each group's
# subdomain (or a wildcard *.{$CHECKIN_DOMAIN} record) at this host.

# Shared per-site config, identical to the single-group Caddyfile.
(checkin_common) {
	# Compress text payloads (JSON, HTML). Caddy skips already-compressed types
	# like image/jpeg and image/png automatically.
	encode zstd gzip

	# Security headers at the edge (server also sets these, belt-and-suspenders).
	header {
		# Pin HTTPS for a year so a network attacker can't SSL-strip the web/PWA client.
		Strict-Transport-Security "max-age=31536000; includeSubDomains"
		X-Content-Type-Options "nosniff"
		X-Frame-Options "DENY"
		Referrer-Policy "no-referrer"
		Permissions-Policy "geolocation=(), camera=(), microphone=()"
		-Server
	}

	# Larger body limit so image uploads pass through.
	request_body {
		max_size 15MB
	}
}

EOF
  emit_site '{$CHECKIN_DOMAIN}' server-main
  for s in "${slugs[@]}"; do
    emit_site "$s.{\$CHECKIN_DOMAIN}" "server-$s"
  done
} > "$CADDY_OUT"

echo "rendered: $COMPOSE_OUT, $CADDY_OUT (groups: main${slugs[*]:+ ${slugs[*]}})"
