package api

import (
	"context"
	"log"
	"net/http"
	"strconv"
	"strings"
	"time"
)

// noCollapse marks a notification that already stands alone on a member's device: a comment,
// a reply, a like, or the daily digest each reach one person once. Only a cross-posted
// check-in fans out into several notifications about the same thing.
const noCollapse = ""

type deviceReq struct {
	Token    string `json:"token"`
	Platform string `json:"platform"` // "ios" | "android"
}

// handleRegisterDevice stores (or refreshes) the caller's FCM token so the server can
// push to this device.
func (s *Server) handleRegisterDevice(w http.ResponseWriter, r *http.Request) {
	var req deviceReq
	if err := decodeJSON(w, r, &req); err != nil {
		writeErr(w, http.StatusBadRequest, "invalid body")
		return
	}
	if strings.TrimSpace(req.Token) == "" {
		writeErr(w, http.StatusBadRequest, "token required")
		return
	}
	if err := s.db.UpsertDeviceToken(r.Context(), userFrom(r).ID, req.Token, req.Platform); err != nil {
		writeErr(w, http.StatusInternalServerError, "server error")
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

// handleUnregisterDevice drops a token (e.g. on logout).
func (s *Server) handleUnregisterDevice(w http.ResponseWriter, r *http.Request) {
	var req deviceReq
	if err := decodeJSON(w, r, &req); err != nil {
		writeErr(w, http.StatusBadRequest, "invalid body")
		return
	}
	if err := s.db.DeleteDeviceToken(r.Context(), req.Token); err != nil {
		writeErr(w, http.StatusInternalServerError, "server error")
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

func (s *Server) handleGetNotificationPrefs(w http.ResponseWriter, r *http.Request) {
	prefs, err := s.db.NotificationPrefs(r.Context(), userFrom(r).ID)
	if err != nil {
		writeErr(w, http.StatusInternalServerError, "server error")
		return
	}
	writeJSON(w, http.StatusOK, prefs)
}

type notifyPrefsReq struct {
	Posts   *bool `json:"posts"`
	Replies *bool `json:"replies"`
	Likes   *bool `json:"likes"`

	DigestEnabled *bool `json:"digestEnabled"`
	DigestHour    *int  `json:"digestHour"`
	DigestOffset  *int  `json:"digestOffset"`
}

// handleUpdateNotificationPrefs sets the caller's notification settings. Omitted fields
// keep their current value, so the app can PATCH just the UTC offset on launch (keeping a
// DST shift from silently moving someone's digest) without restating everything else.
func (s *Server) handleUpdateNotificationPrefs(w http.ResponseWriter, r *http.Request) {
	var req notifyPrefsReq
	if err := decodeJSON(w, r, &req); err != nil {
		writeErr(w, http.StatusBadRequest, "invalid body")
		return
	}
	prefs, err := s.db.NotificationPrefs(r.Context(), userFrom(r).ID)
	if err != nil {
		writeErr(w, http.StatusInternalServerError, "server error")
		return
	}
	if req.Posts != nil {
		prefs.Posts = *req.Posts
	}
	if req.Replies != nil {
		prefs.Replies = *req.Replies
	}
	if req.Likes != nil {
		prefs.Likes = *req.Likes
	}
	if req.DigestEnabled != nil {
		prefs.DigestEnabled = *req.DigestEnabled
	}
	if req.DigestHour != nil {
		prefs.DigestHour = *req.DigestHour
	}
	if req.DigestOffset != nil {
		prefs.DigestOffset = *req.DigestOffset
	}
	prefs = prefs.Normalize()
	if err := s.db.SetNotificationPrefs(r.Context(), userFrom(r).ID, prefs); err != nil {
		writeErr(w, http.StatusInternalServerError, "server error")
		return
	}
	writeJSON(w, http.StatusOK, prefs)
}

// collapseFor builds the push collapse id for one kind of notification about one shared
// comment, or noCollapse when the comment was not sent to several groups (the ordinary
// single-group case, where there is nothing to collapse against).
// The kind prefix is what keeps different EVENTS about the same shared id apart. A comment
// that is also a reply fires two notifications, and a cross-posted check-in's own id is
// generated by the same client in the same way as a comment's - so without a prefix a post's
// collapse key and a comment's could be the same string and one would replace the other.
//
// The id itself cannot be authenticated server-side, and that is inherent rather than an
// oversight: the servers holding the copies never talk to each other, and a member's user id
// differs on each of them, so the client-generated id is the only thing they share. It is 16
// bytes from a secure source, so a collision between two members' ids is not a practical
// concern; what the prefix removes is the collision that could happen by construction.
func collapseFor(kind, sharedID string) string {
	if sharedID == "" {
		return noCollapse
	}
	return kind + ":" + sharedID
}

// notifyPost pushes a new-post notification to everyone opted in except the author. It
// runs in its own goroutine off the request path, so it uses a background context.
//
// crossPostID is the shared id of a check-in posted to several groups at once, or empty for
// an ordinary post. Every copy notifies its own group, so someone in more than one of them
// would otherwise get the same check-in announced several times; collapsing on that id
// leaves one notification on their device.
func (s *Server) notifyPost(authorID int64, authorName string, postID int64, crossPostID string) {
	if s.push == nil {
		return
	}
	// This runs in its own goroutine off the request path, so it's outside chi's
	// Recoverer — a panic here would crash the whole process. Recover, and bound the
	// work with a timeout so a slow FCM call can't leak goroutines.
	defer func() {
		if rec := recover(); rec != nil {
			log.Printf("notifyPost: recovered: %v", rec)
		}
	}()
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	tokens, err := s.db.TokensForNewPost(ctx, authorID)
	if err != nil || len(tokens) == 0 {
		return
	}
	s.push.Send(ctx, tokens, s.serverName(ctx), authorName+" shared a check-in",
		s.pushData("post", postID), collapseFor("post", crossPostID))
}

// notifyReply pushes a reply notification to the post's author.
//
// crossCommentID, when the comment was sent to several groups at once, collapses those
// groups' separate pushes into one entry on the device - a member of all three groups said
// one thing and should be told about it once. Prefixed rather than used raw so that a
// comment which is ALSO a reply cannot collapse its two different notifications ("commented
// on your check-in" and "replied to your comment") into a single one, which would silently
// drop whichever arrived first.
func (s *Server) notifyReply(commenterName string, postID, commenterID int64, crossCommentID string) {
	if s.push == nil {
		return
	}
	defer func() {
		if rec := recover(); rec != nil {
			log.Printf("notifyReply: recovered: %v", rec)
		}
	}()
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	tokens, err := s.db.TokensForReply(ctx, postID, commenterID)
	if err != nil || len(tokens) == 0 {
		return
	}
	s.push.Send(ctx, tokens, s.serverName(ctx), commenterName+" commented on your check-in",
		s.pushData("comment", postID), collapseFor("comment", crossCommentID))
}

// notifyCommentReply pushes a reply notification to the author of the comment being replied
// to. The parent comment lives on this same server, so its author resolves with a local
// join — no cross-group coordination even when the post is a cross-post.
//
// crossCommentID collapses the copies the same way notifyReply's does, under its own
// prefix - see that function's doc comment.
func (s *Server) notifyCommentReply(replierName string, postID, parentCommentID, replierID int64, crossCommentID string) {
	if s.push == nil {
		return
	}
	defer func() {
		if rec := recover(); rec != nil {
			log.Printf("notifyCommentReply: recovered: %v", rec)
		}
	}()
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	tokens, err := s.db.TokensForCommentReply(ctx, parentCommentID, replierID)
	if err != nil || len(tokens) == 0 {
		return
	}
	s.push.Send(ctx, tokens, s.serverName(ctx), replierName+" replied to your comment",
		s.pushData("reply", postID), collapseFor("reply", crossCommentID))
}

// notifyLike pushes a like notification to the post's author.
func (s *Server) notifyLike(likerName string, postID, likerID int64) {
	if s.push == nil {
		return
	}
	defer func() {
		if rec := recover(); rec != nil {
			log.Printf("notifyLike: recovered: %v", rec)
		}
	}()
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	tokens, err := s.db.TokensForLike(ctx, postID, likerID)
	if err != nil || len(tokens) == 0 {
		return
	}
	s.push.Send(ctx, tokens, s.serverName(ctx), likerName+" liked your check-in",
		s.pushData("like", postID), noCollapse)
}

// pushData builds the data payload for a push message. Besides the post reference it
// carries this server's identity ("server": public base URL) so an app connected to
// several servers can attribute the notification — post ids alone collide across servers.
func (s *Server) pushData(kind string, postID int64) map[string]string {
	data := map[string]string{"type": kind, "postId": strconv.FormatInt(postID, 10)}
	if s.cfg.PublicURL != "" {
		data["server"] = s.cfg.PublicURL
	}
	return data
}
